# Import các thư viện

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# Đọc dữ liệu

In [7]:
df = pd.read_csv("../../Data/Created Data/hotel_bookings_cleaned.csv")
df

,arrival_date,reservation_status_date,hotel,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,...,children,babies,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,continent
0,2015-07-01,2015-07-01,Resort Hotel,BB,PRT,Direct,Direct,C,C,No Deposit,...,0,0,0,0,3,0,0.00,0,0,Europe
1,2015-07-01,2015-07-01,Resort Hotel,BB,PRT,Direct,Direct,C,C,No Deposit,...,0,0,0,0,4,0,0.00,0,0,Europe
2,2015-07-01,2015-07-02,Resort Hotel,BB,GBR,Direct,Direct,A,C,No Deposit,...,0,0,0,0,0,0,75.00,0,0,Europe
3,2015-07-01,2015-07-02,Resort Hotel,BB,GBR,Corporate,Corporate,A,A,No Deposit,...,0,0,0,0,0,0,75.00,0,0,Europe
4,2015-07-01,2015-07-03,Resort Hotel,BB,GBR,Online TA,TA/TO,A,A,No Deposit,...,0,0,0,0,0,0,98.00,0,1,Europe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87360,2017-08-30,2017-09-06,City Hotel,BB,BEL,Offline TA/TO,TA/TO,A,A,No Deposit,...,0,0,0,0,0,0,96.14,0,0,Europe
87361,2017-08-31,2017-09-07,City Hotel,BB,FRA,Online TA,TA/TO,E,E,No Deposit,...,0,0,0,0,0,0,225.43,0,2,Europe
87362,2017-08-31,2017-09-07,City Hotel,BB,DEU,Online TA,TA/TO,D,D,No Deposit,...,0,0,0,0,0,0,157.71,0,4,Europe
87363,2017-08-31,2017-09-07,City Hotel,BB,GBR,Online TA,TA/TO,A,A,No Deposit,...,0,0,0,0,0,0,104.40,0,0,Europe
87364,2017-08-29,2017-09-07,City Hotel,HB,DEU,Online TA,TA/TO,A,A,No Deposit,...,0,0,0,0,0,0,151.20,0,2,Europe

# chuyển 2 cột date thành kiểu datetime trước rồi tiếp tục làm việc

In [8]:
def change_df(df):
    format_year = "%Y-%m-%d"

    df["arrival_date"] = pd.to_datetime(df["arrival_date"], format=format_year)
    df["reservation_status_date"] = pd.to_datetime(
        df["reservation_status_date"], format=format_year
    )


change_df(df)